- id: github-distributed-owners
  name: GitHub Distributed Owners
  description: Auto generate a GitHub compatible CODEOWNERS files from OWNERS files distributed through the file tree.
  entry: github-distributed-owners
  language: rust
  types: [file, text]
  args: ["--output-file=.github/CODEOWNERS"]
  pass_filenames: false
  require_serial: true
