body:
  - type: markdown
    attributes:
      value: |
        # Thank You For Sharing With Us!
        Thank you for taking the time to share about your use with us. Whether you love it (:tada:) or hate it
        (:disappointed:), feedback is how we improve.
  - type: input
    id: who
    attributes:
      label: Who are you?
      description: Company, team, project, or person, who is using github-distributed-owners?
      placeholder: Company, team, project, or person
    validations:
      required: true
  - type: dropdown
    id: impression
    attributes:
      label: What do you think?
      description: Do you love it, hate it, etc?
      options:
        - "💙 I love it"
        - "😕 It's complicated"
        - "🥱 It's... fine. Meh"
        - "😰 I hate it"
    validations:
      required: true
  - type: textarea
    id: thoughts
    attributes:
      label: Thoughts
      description: Care to elaborate?
    validations:
      required: false
  - type: checkboxes
    id: logo
    attributes:
      label: Can we display your logo as a user?
      options:
        - label: "Yes"
    validations:
      required: false
