name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    name: cargo-deny
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources

    # Don't fail CI for advisories
    continue-on-error: ${{ matrix.checks == 'advisories' }}

    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          rust-version: '1.70.0'
          command: check ${{ matrix.checks }}
